name: Simple CI Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f1002714@ds.study.iitm.ac.in
        run: echo "Hello, world! GitHub Actions is running successfully!"
